import React from 'react'
import type { Metadata } from 'next'
import PostList from '@/components/PostList'
import PostPagination from '@/components/PostPagination'

import { allPosts, Post } from 'contentlayer/generated'
import { getPagination } from '@/utils/Pagination'
const posts : Post[] = allPosts.sort((a,b)=>b.date.localeCompare(a.date))

export const metadata: Metadata = {
  title: 'Lista de todos los Post',
  description: 'Description post - Generated by create next app',
}

const Post = () => {

  const {currentPost, totalPages}=getPagination(allPosts,2)

  return (
    <div>
      <div className="grid gap-4">
        <PostList posts={currentPost}/>
        {totalPages > 1 && <PostPagination totalPages={totalPages}/>}
      </div>
    </div>
  )
}

export default Post